name: pequi
description: "Pequi is a enviroment manager package that allow you to white label your application as you like"
author: "James Yan <jamesyancm@gmail.com>"
homepage: "https://github.com/jamesmacedo/pequi"
version: 1.0.8

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  args: ^2.6.0
  flutter:
    sdk: flutter
  xml: ^6.5.0
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
